### ISSUE TITLE
YYC throws uninitialised variable GM: V1.4.1760

### ISSUE THREAD

**Issue by joakimFF** [RaniSputnik/Flox-GML#4]
unable to compile on YYC targets compile log is: 

Create started: 21:32:53
"C:\Users\Optimus Prime\AppData\Roaming\GameMaker-Studio\GMAssetCompiler.exe" /llvmSource="C:\Users\Optimus Prime\AppData\Roaming\GameMaker-Studio\YYC" /c /m=llvm-win  /config="Default" /tgt=64 /obob=True /obpp=False /obru=True /obes=False /i=3 /j=12 /cvm /tp=2048 /mv=1 /iv=0 /rv=0 /bv=1760 /gn="FeralFury_BETA2_AUG" /td="C:\Users\Optimus Prime\AppData\Local" /cd="C:\Users\Optimus Prime\Documents\GameMaker\Cache" /sh=True /dbgp="6502" /hip="192.168.0.12" /hprt="51268" /optionsini="C:\Users\Optimus Prime\AppData\Local\gm_ttt_65621\gm_ttt_43961\options.ini" /o="C:\Users\Optimus Prime\AppData\Local\gm_ttt_65621\gm_ttt_43961" "C:\Users\Optimus Prime\Dropbox\backups\FeralFury_BETA2_AUG.gmx\FeralFury_BETA2_AUG.project.gmx" 

Reading project file....finished.
Compile Constants...finished.
Remove DnD...finished.
Compile Scripts...finished.
Compile Objects...finished.
Compile Timelines...finished.
Compile Triggers...finished.
Compile Rooms...finished.
Compile Extensions...finished.
Global scripts...finished.
Final Compile...Error : gml_Script_flox_init(31) : using uninitialised variable 'gameID'
Error : gml_Script_flox_init(32) : using uninitialised variable 'gameKey'
Error : gml_Script_flox_init(33) : using uninitialised variable 'gameVersion'
Error : gml_Script_flox_init(58) : using uninitialised variable 'gameID'
Error : gml_Script_flox_init(58) : using uninitialised variable 'gameVersion'
Error : gml_Script_i_flox_request_perform(73) : using uninitialised variable 'gameKey'
Error : gml_Script_i_flox_request_perform(97) : using uninitialised variable 'gameID'
Error : gml_Script_i_flox_persistent_load(12) : using uninitialised variable 'gameID'
Error : gml_Script_i_flox_persistent_load(15) : using uninitialised variable 'gameKey'
Error : gml_Script_i_flox_persistent_load(16) : using uninitialised variable 'gameKey'
Error : gml_Script_i_flox_persistent_save(16) : using uninitialised variable 'gameID'
Error : gml_Script_i_flox_persistent_save(18) : using uninitialised variable 'gameKey'
finished.
Stats : GMA : Elapsed=56862,2524
Stats : GMA : sp=912,au=153,bk=203,pt=64,sc=1240,sh=87,fo=14,tl=0,ob=1914,ro=526,da=0,ex=10,ma=2866,fm=0xDFFF2FF5
Create finished: 21:33:59

**Comment by studiofurukawa** [comment]
Game maker changed the way they handle Self. and Vars after the newest update.

I found a hotfix.

```
gameId = "Your ID";
gameID = gameId
gameKey = "Your Game Key";

// This can be whatever you like, it is used to keep track
// of what version of your game players are playing.
gameVersion = "Your Version";
// Initialize flox with all the settings above
flox_init(gameId,gameKey,gameVersion);
```

Ill be watching this to see if there is a better way to fix,

**Comment by RaniSputnik** [comment]
Thanks @studiofurukawa, should be fixed in the next release. See [this commit](https://github.com/RaniSputnik/Flox-GML/commit/5bd01d50c20055ba0935e46eee3a5d61f6ba1629)
