### ISSUE TITLE
Failed to save persistent data

### ISSUE THREAD

**Issue by sunch1ld** [RaniSputnik/Flox-GML#6]
Hi 

I am using Android 6.1 with Motorola 4 Plus and Game Maker Studio 1.4.1763. Flox flox-gml.0.5.2.

I am using Target SDK 16, Min SDK 15 Compile SDK 23. Build Tools 23.0.3 and SupportLib 23.2.1.

When I try to initialize flox calling flox_init script I see that log messages

01-03 11:39:40.274 29306 29350 I yoyo    : Flox: Loading persistent data
01-03 11:39:40.274 29306 29350 I yoyo    : Flox: No persistent data found, this is likely to be the first time this game has run
01-03 11:39:40.277 29306 29350 I yoyo    : Flox: Request created with map, this will soon be removed
01-03 11:39:40.278 29306 29350 I yoyo    : Flox: [Info] Game Started
01-03 11:39:40.281 29306 29350 I yoyo    : start time 1690
01-03 11:39:40.282 29306 29350 I yoyo    : android.software.leanback = 0
01-03 11:39:40.282 29306 29350 I yoyo    : MANUFACTURER = motorola
01-03 11:39:40.316 29306 29350 I yoyo    : Flox: Making Request Method=POST Path=logs
01-03 11:39:40.317 29306 29350 I yoyo    : HttpRequest("https://www.flox.cc/api/games/123Rxxf1MkBZsgCt/logs", "POST", "{ "deviceInfo": { "resolution": "1920x1080", "os": "Android" }, "languageCode": "it", "installationId": "3EE1H0ocGooausm1", "startTime": "2017-01-03T10:39:40Z", "gameVersion": "0.1" }", 0)
01-03 11:39:40.318 29306 29350 I yoyo    : Flox: Saving persistent data
01-03 11:39:40.322 29306 29350 I yoyo    : Flox: Failed to save persistent data 'assets/Flox.123Rxxf1MkBZsgCt.data'
01-03 11:39:40.326 29306 29413 I yoyo    : Setting do output to true
01-03 11:39:40.327 29306 29413 I yoyo    : HttpRequest: Found header Content-Type: application/json
01-03 11:39:40.327 29306 29413 I yoyo    : HttpRequest: Found header X-Flox: {"player":{"id":"3p4hD2hhyEAT9Lee","authType":"guest"},"dispatchTime":"2017-01-03T10:39:40Z","sdk":{"type":"gml","version":"0.5.2"},"bodyCompression":"none","gameKey":"123WfuXdbzH69ylL"}
01-03 11:39:40.898 29306 29413 I yoyo    : HttpRequest: Got response code '204'
01-03 11:39:40.899 29306 29413 I yoyo    : HttpResult
01-03 11:39:40.899 29306 29413 I yoyo    : done memcopy 1  pBytes
01-03 11:39:40.900 29306 29350 I yoyo    : Flox: Processing response for path = logs
01-03 11:39:40.900 29306 29350 I yoyo    : Flox: Flox request successful
01-03 11:39:40.902 29306 29350 I yoyo    : Flox: Saving persistent data
01-03 11:39:40.902 29306 29350 I yoyo    : Flox: Failed to save persistent data 'assets/Flox.123Rxxf1MkBZsgCt.data'
01-03 11:39:48.744 29306 29350 I yoyo    : end time 10153

something went wrong while flox save data? What can I do to solve that problem?

thanks

**Comment by RaniSputnik** [comment]
Hi @sunch1ld, thanks for opening this issue.

I believe that data has been saved successfully in this case, you should find in the appdata directory (where GameMaker usually saves game data) that there is a file Flox.123Rxxf1MkBZsgCt.data. This has been fixed in [this commit](https://github.com/RaniSputnik/Flox-GML/commit/8696c087d06f2fefddb34eb46abb5080400d9a3b), you can see I was assuming that ```ds_map_secure_save``` would return true/false to indicate success.

Hope that helps, I hope to release these changes soon.

Cheers, Ryan.
